---
abstract: 'Fennec wrapper for L<Test::Deep>'
author:
  - 'ben hengst <notbenh@cpan.org>'
build_requires:
  Fennec: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Fennec-Assert-Wrapper-Deep
provides:
  Fennec::Assert::Wrapper::Deep:
    file: lib/Fennec/Assert/Wrapper/Deep.pm
    version: 0.02
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
